### ISSUE TITLE
markers not displaying on map

### ISSUE THREAD

**Issue by apjmason** [CPHDH/theme-curatescape-echo#3]
Love the new theme design! The individual item maps work well on my site, and the modal button overlay map shows all markers as expected, but the home page map and items/map page load only the base map with no markers.  

[https://hhfinals.dgah.sites.carleton.edu/carlclubs/items/map](https://hhfinals.dgah.sites.carleton.edu/carlclubs/items/map)

System info:

```
Omeka 3.0.2
CuratescapeAdminHelper	1.3.3
CuratescapeJSON	1.2.6
Geolocation	3.2.2
curatescape-echo	1.0.5 
```

Error messages from the console:

```
bigfoot.js?v=3.0.2:636 Uncaught ReferenceError: jQuery is not defined
    at bigfoot.js?v=3.0.2:636:6
    at bigfoot.js?v=3.0.2:638:4
(anonymous) @ bigfoot.js?v=3.0.2:636
(anonymous) @ bigfoot.js?v=3.0.2:638

map:56 Uncaught ReferenceError: jQuery is not defined
    at map:56:19
(anonymous) @ map:56

multi-map.js:129          GET https://hhfinals.dgah.sites.carleton.edu/items/browse?output=mobile-json 404
(anonymous) @ multi-map.js:129
load (async)
loadJS @ map:86
(anonymous) @ multi-map.js:106
load (async)
loadJS @ map:86
(anonymous) @ multi-map.js:105
load (async)
loadJS @ map:86
loadMapMulti @ multi-map.js:104
(anonymous) @ multi-map.js:420
scrollEvents @ multi-map.js:418

VM1691:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)
(anonymous) @ multi-map.js:131
load (async)
loadJS @ map:86
(anonymous) @ multi-map.js:106
load (async)
loadJS @ map:86
(anonymous) @ multi-map.js:105
load (async)
loadJS @ map:86
loadMapMulti @ multi-map.js:104
(anonymous) @ multi-map.js:420
scrollEvents @ multi-map.js:418
```

Thanks!

**Comment by ebellempire** [comment]
Hi @apjmason, looks like the issue involves either a third-party plugin or some customization. I'm not sure where `bigfoot.js` is being loaded but it's not from any Curatescape code. Since `bigfoot.js` requires `jQuery`, it's always going to break. I made the decision to only include jQuery in a few areas where it was required for core functionality. See [header.php lines 57-65](https://github.com/CPHDH/theme-curatescape-echo/blob/master/curatescape-echo/common/header.php#L57-L65). I'm blocking and/or delaying some plugin assets to improve initial loading times. You may need to make changes there.

**Comment by apjmason** [comment]
Thanks! Yes, I realized that too and uninstalling the other plugin fixed the first two errors. 

The issue with multi-map.js, however, was due to the fact that our install is in a subdirectory. I fixed it (in a brittle way) by explicitly adding it to line 94

```
--- multi-map.js	2022-01-12 14:13:32.000000000 -0600
+++ multi-map-mod.js	2022-03-09 08:00:22.000000000 -0600
@@ -91,7 +91,7 @@
     ? window.location.protocol +
       "//" +
       window.location.hostname +
-      "/items/browse" +
+      "/carlclubs/items/browse" +
       jsonPath
     : url + jsonPath;
   if (mapfigure && mapped == 0) {
```

There were several relative links throughout the site that also were broken due to the subdirectory install that I was able to fix by wrapping them in omeka's url() function. Happy to submit a PR with those changes if helpful.

**Comment by ebellempire** [comment]
Thanks, I'll merge the pull request in a bit.
