### ISSUE TITLE
Additional Simple Pages not in Menu

### ISSUE THREAD

**Issue by thorsted** [CPHDH/theme-curatescape-echo#5]
I can't seem to have an additional page show up in the Menu. Also is it possible to add additional pages to top with stories, map, etc

**Comment by ebellempire** [comment]
Hi @thorsted, you can change the navigation options in theme settings. See screenshot below. For general questions, please use the [Curatescape Forum](https://forum.curatescape.org ).

<img width="658" alt="Screenshot 2023-05-22 at 9 26 33 AM" src="https://github.com/CPHDH/theme-curatescape-echo/assets/441279/7a1dcc23-9086-4790-a021-9147d2e18e98">
